### ISSUE TITLE
OPL-CL additional support

### ISSUE THREAD

**Issue by J013k** [IcySon55/OPL-Theme-Editor#1]
Sorry for opening new issue, but is there a way to also post your original topic from PSX-Scene about OPL-CL:
[http://psx-scene.com/forums/f150/open-ps2-loader-compatibility-list-site-132906/](http://psx-scene.com/forums/f150/open-ps2-loader-compatibility-list-site-132906/).
Mirror:
[https://web.archive.org/web/20160815000210/http://psx-scene.com/forums/f150/open-ps2-loader-compatibility-list-site-132906/](https://web.archive.org/web/20160815000210/http://psx-scene.com/forums/f150/open-ps2-loader-compatibility-list-site-132906/).

At PSX-Place:
[https://www.psx-place.com/forums/open-ps2-loader-opl.77/](https://www.psx-place.com/forums/open-ps2-loader-opl.77/).

Is something wrong will happens to the server someone can also report about it via additional site.

**Comment by IcySon55** [comment]
I would if I had the time. I can't devote myself to anything other than keeping it running. It only went down because of a local IP change I had to make and forgot that it would affect the site. Sorry.

**Comment by J013k** [comment]
Thanks for your support all these years for PS2 scene.
I understand that you're busy currently in real life,
so I wish you all the best.

Best regards.
